image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start MongoDB
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data

  - name: Setup Git Hooks
    init: git config core.hooksPath .hooks
    command: deno task test
