image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start MongoDB
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data

  - name: Setup Git Hooks
    init: git config core.hooksPath .hooks
    command: |
      export MONGO_URL=mongodb://127.0.0.1:27017
      deno task test
