image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start MongoDB
    init: docker build -t hyper-mongodb .mongodb
    command: |
      mkdir -p /workspace/data
      docker run -it -p 27017:27017 -v /workspace/data:/data/db hyper-mongodb

  - name: Setup Git Hooks
    init: deno task prepare
    command: |
      export MONGO_URL=mongodb://127.0.0.1:27017
      deno task test
