name: 💾 Test & Publish Adapter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.x]
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: ⚡ Run Tests
        run: |
          deno task test
        env:
          CI: true

  # Run the test suite against a Mongo Instance Self Hosted
  # using the mongodb: protocol
  # 
  # This is meant to represent a self-hosted instance of MongoDB
  test-native-integration-self-hosted:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.x]
        mongodb-version: [6]
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      # Start a Mongo Instance in the local CI runner environment
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: ⚡ Run Native Integration Tests
        run: |
          deno task test:integration-native
        env:
          CI: true
          MONGO_URL: mongodb://127.0.0.1:27017

  # Run the test suite against a Mongo Instance Deployed on MongoDB Atlas
  # a common hosting platform for MongoDB.
  # 
  # The main distinction is that MongoDB Atlas uses the mongodb+srv: protocol
  test-native-integration-atlas:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.x]
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: ⚡ Run Native Integration Tests (Atlas 🧭)
        run: |
          deno task test:integration-native
        env:
          CI: true
          MONGO_URL: ${{ secrets.INTEGRATION_ATLAS_MONGO_URL }}

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test, test-native-integration-self-hosted, test-native-integration-atlas]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
