name: Test

on:
  push:
    branches:
      - main
      - "**"
    tags-ignore:
      - "*"

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.13.x, 1.14.x]
        mongodb-version: [4.0]
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: ./scripts/test.sh
        env:
          CI: true
  integrated:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.13.x, 1.14.x]
        mongodb-version: [4.0]
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: ./scripts/harness.sh
      - run: ./scripts/ci.sh
        env:
          HYPER: http://localhost:6363/test
          CI: true
