name: Test

on:
  push:
    branches: "*"
    tags-ignore: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.12.x]
        mongodb-version: [4.0]
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: ./scripts/test.sh
        env:
          CI: true
